### ISSUE TITLE
JSON and XHTML need to properly escape values

### ISSUE THREAD

**Issue by christopheradams** [fontlibrary/fontaine#3]
In the case of JSON for example it only appears to escape quotation marks, and not backslashes or any other special characters. This can result in invalid JSON in the output. XHTML also needs values escaped.

**Comment by christopheradams** [comment]
For JSON something like 8c7421a might work

**Comment by christopheradams** [comment]
PR for JSON escaping is here https://github.com/fontlibrary/fontaine/pull/4/files

**Comment by ChristTrekker** [comment]
Code has been committed.

**Comment by christopheradams** [comment]
JSON was addressed but has anyone looked at XHTML? Does anyone use it for output?

**Comment by ChristTrekker** [comment]
I use the XHTML output for my font pages all the time. (Though, it seems most of the web has gone away from XHTML to HTML5.) I haven't verified we're escaping things properly, because I haven't noticed anything obviously broken.
